version: '3.8'

services:
  yaqin-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=https://kiwzebpbftpxmjzlrxzo.supabase.co
        - VITE_SUPABASE_ANON_KEY=sb_publishable_SUguTwt-uxKFy-IAW9ORtg_mTPkrXw-
    container_name: yaqin-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - BOT_TOKEN=8972376368:AAHJ7FBA-1kZf-VKaDHff0JKv78wQ2oadhY
      - VITE_SUPABASE_URL=https://kiwzebpbftpxmjzlrxzo.supabase.co
      - VITE_SUPABASE_ANON_KEY=sb_publishable_SUguTwt-uxKFy-IAW9ORtg_mTPkrXw-
      - JWT_SECRET=yaqin_super_secret_jwt_key_2026_modern_dating_network
